// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type SecretScheme = {
  secret_text: string;
  password: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type TakeSecretSecretsSecretKeyGetData = {
  path: {
    secret_key: string;
  };
  query: {
    password: string;
  };
};

export type TakeSecretSecretsSecretKeyGetResponse = unknown;

export type TakeSecretSecretsSecretKeyGetError = HTTPValidationError;

export type CreateSecretGeneratePostData = {
  body: SecretScheme;
};

export type CreateSecretGeneratePostResponse = unknown;

export type CreateSecretGeneratePostError = HTTPValidationError;
