// This file is auto-generated by @hey-api/openapi-ts

export type Card = {
  front_side: string;
  back_side: string;
  id: number;
  owner_id: number;
};

export type CardCreate = {
  front_side: string;
  back_side: string;
};

export type Collection = {
  title: string;
  description?: string | null;
  id: number;
  owner_id: number;
};

export type CollectionCreate = {
  title: string;
  description?: string | null;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type TrainRecord = {
  meta_data: string;
  id: number;
  card_id: number;
  user_id: number;
};

export type TrainRecordCreate = {
  meta_data: string;
};

export type User = {
  nickname: string;
  email: string;
  id: number;
};

export type UserAuth = {
  email: string;
  password: string;
};

export type UserBase = {
  nickname: string;
  email: string;
};

export type UserCreate = {
  nickname: string;
  email: string;
  password: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type ReadCardCardsCardIdGetData = {
  path: {
    card_id: number;
  };
};

export type ReadCardCardsCardIdGetResponse = Card;

export type ReadCardCardsCardIdGetError = HTTPValidationError;

export type DeleteCardCardsCardIdDeleteData = {
  path: {
    card_id: number;
  };
};

export type DeleteCardCardsCardIdDeleteResponse = unknown;

export type DeleteCardCardsCardIdDeleteError = HTTPValidationError;

export type UpdateCardCardsCardIdPutResponse = unknown;

export type UpdateCardCardsCardIdPutError = unknown;

export type ReadCardsCardsGetData = {
  query?: {
    limit?: number | null;
    skip?: number;
  };
};

export type ReadCardsCardsGetResponse = Array<Card>;

export type ReadCardsCardsGetError = HTTPValidationError;

export type CreateCardCardsPostData = {
  body: CardCreate;
};

export type CreateCardCardsPostResponse = Card;

export type CreateCardCardsPostError = HTTPValidationError;

export type ReadCardCollectionsCardsCardIdCollectionsGetResponse = unknown;

export type ReadCardCollectionsCardsCardIdCollectionsGetError = unknown;

export type ReadCollectionCollectionsCollectionIdGetData = {
  path: {
    collection_id: number;
  };
};

export type ReadCollectionCollectionsCollectionIdGetResponse = Collection;

export type ReadCollectionCollectionsCollectionIdGetError = HTTPValidationError;

export type ReadCollectionsCollectionsGetData = {
  query?: {
    limit?: number | null;
    skip?: number;
  };
};

export type ReadCollectionsCollectionsGetResponse = Array<Collection>;

export type ReadCollectionsCollectionsGetError = HTTPValidationError;

export type CreateCollectionCollectionsPostData = {
  body: CollectionCreate;
};

export type CreateCollectionCollectionsPostResponse = Collection;

export type CreateCollectionCollectionsPostError = HTTPValidationError;

export type ReadCollectionCardsCollectionsCollectionIdCardsGetData = {
  path: {
    collection_id: number;
  };
};

export type ReadCollectionCardsCollectionsCollectionIdCardsGetResponse =
  Array<Card>;

export type ReadCollectionCardsCollectionsCollectionIdCardsGetError =
  HTTPValidationError;

export type SetCardCollectionConnectionCollectionsCollectionIdPairPostData = {
  body: Array<number>;
  path: {
    collection_id: number;
  };
};

export type SetCardCollectionConnectionCollectionsCollectionIdPairPostResponse =
  unknown;

export type SetCardCollectionConnectionCollectionsCollectionIdPairPostError =
  HTTPValidationError;

export type DeleteCardCollectionConnectionCollectionsCollectionIdUnpairDeleteData =
  {
    body: Array<number>;
    path: {
      collection_id: number;
    };
  };

export type DeleteCardCollectionConnectionCollectionsCollectionIdUnpairDeleteResponse =
  unknown;

export type DeleteCardCollectionConnectionCollectionsCollectionIdUnpairDeleteError =
  HTTPValidationError;

export type CreateTrainRecordTrainRecordsCardIdPostData = {
  body: TrainRecordCreate;
  path: {
    card_id: number;
  };
};

export type CreateTrainRecordTrainRecordsCardIdPostResponse = TrainRecord;

export type CreateTrainRecordTrainRecordsCardIdPostError = HTTPValidationError;

export type ReadCardLastTrainRecordTrainRecordsRecordCardIdGetData = {
  path: {
    card_id: number;
  };
};

export type ReadCardLastTrainRecordTrainRecordsRecordCardIdGetResponse =
  Array<TrainRecord>;

export type ReadCardLastTrainRecordTrainRecordsRecordCardIdGetError =
  HTTPValidationError;

export type ReadUserUsersProfileGetResponse = User;

export type ReadUserUsersProfileGetError = unknown;

export type CreateUserUsersRegisterPostData = {
  body: UserCreate;
};

export type CreateUserUsersRegisterPostResponse = User;

export type CreateUserUsersRegisterPostError = HTTPValidationError;

export type UpdateUserUsersEditProfilePutData = {
  body: UserBase;
};

export type UpdateUserUsersEditProfilePutResponse = User;

export type UpdateUserUsersEditProfilePutError = HTTPValidationError;

export type AuthenticateUserUsersLoginPostData = {
  body: UserAuth;
};

export type AuthenticateUserUsersLoginPostResponse = unknown;

export type AuthenticateUserUsersLoginPostError = HTTPValidationError;

export type LogoutUserUsersLogoutPostResponse = unknown;

export type LogoutUserUsersLogoutPostError = unknown;

export type DeleteUserUsersDeleteProfileDeleteResponse = unknown;

export type DeleteUserUsersDeleteProfileDeleteError = unknown;

export type ReadCardsAdminCardsGetData = {
  query?: {
    limit?: number | null;
    skip?: number;
  };
};

export type ReadCardsAdminCardsGetResponse = Array<Card>;

export type ReadCardsAdminCardsGetError = HTTPValidationError;

export type ReadTrainRecordsAdminTrainRecordsGetData = {
  query?: {
    limit?: number | null;
    skip?: number;
  };
};

export type ReadTrainRecordsAdminTrainRecordsGetResponse = Array<TrainRecord>;

export type ReadTrainRecordsAdminTrainRecordsGetError = HTTPValidationError;

export type ReadUsersAdminUsersGetData = {
  query?: {
    limit?: number;
    skip?: number;
  };
};

export type ReadUsersAdminUsersGetResponse = Array<User>;

export type ReadUsersAdminUsersGetError = HTTPValidationError;

export type ReadCollectionsAdminCollectionsGetData = {
  query?: {
    limit?: number | null;
    skip?: number;
  };
};

export type ReadCollectionsAdminCollectionsGetResponse = Array<Collection>;

export type ReadCollectionsAdminCollectionsGetError = HTTPValidationError;
